# -*- coding: utf-8 -*-
"""Will a Driver accept the Coupon?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UquwLrX0Ben12Xslp7mDqlVUciTsjhO1

# Data 
Link: https://archive.ics.uci.edu/ml/datasets/in-vehicle+coupon+recommendation

## What does it say?
This data was collected via a survey on Amazon Mechanical Turk. The survey describes different driving scenarios including the destination, current time, weather, passenger, etc., and then ask the person whether he will accept the coupon if he is the driver.

## Task
- Classification (Binary)
"""

# Commented out IPython magic to ensure Python compatibility.
# Import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

data = pd.read_csv("drive/My Drive/colab notebooks/in-vehicle-coupon-recommendation.csv")

data

data.isna().sum()

data.info()

def preprocess_inputs(df):
  df = df.copy()
  df = df.drop("car", axis=1)
  df['Bar'] = df.fillna(df['Bar'].mode())
  df['CoffeeHouse'] = df.fillna(df['CoffeeHouse'].mode())
  df['CarryAway'] = df.fillna(df['CarryAway'].mode())
  df['RestaurantLessThan20'] = df.fillna(df['RestaurantLessThan20'].mode())
  return df

X = preprocess_inputs(data)

X

X.info()

X.isna().sum()

X['Restaurant20To50'] = X.fillna(X['Restaurant20To50'].mode())

X.isna().sum()

!pip install pycaret

import pycaret.classification as pyc

pyc.setup(
    data = X,
    target = 'Y',
    train_size=0.8,
    normalize = True
)

pyc.compare_models()

best_model = pyc.create_model('lightgbm')

print(best_model)

pyc.evaluate_model(best_model)

pyc.save_model(best_model, "lightgbm")